version: "3.9"

services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    container_name: housing-backend
    ports:
      - "5000:5000"
    volumes:
      - ./app/backend/logs:/app/logs
    environment:
      - MODEL_NAME=housing-price-model
      - MODEL_VERSION=latest

  frontend:
    build: ./app/frontend
    container_name: housing-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5000
    restart: always
