version: "3.9"

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.10.2
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    command: >
      mlflow server
      --backend-store-uri /mlruns
      --default-artifact-root /mlruns
      --host 0.0.0.0
      --port 5000

  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    container_name: housing-backend
    ports:
      - "5001:5001"
    volumes:
      - ./logs:/app/logs
      - ./mlruns:/app/mlruns
      - ./data:/app/data
      - ./config:/app/config
      - ./src:/src
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MODEL_NAME=housing-price-model
      - MODEL_VERSION=latest
